// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  tutorialSidebar: [
    'welcome-and-overview',
    'docker-intro', 
    'docker-installation',
    {
      type: 'category',
      label: 'Full stack with Docker',
      items: [
        'full-stack-w-docker/section-overview',
        {
          type: 'category',
          label: 'Authentication',
          items: [
            'full-stack-w-docker/authentication/authentication',
            'full-stack-w-docker/authentication/frontend',
            'full-stack-w-docker/authentication/backend'
          ],
        },
        {
          type: 'category',
          label: 'Tasks',
          items: [
            'full-stack-w-docker/tasks/tasks',
            'full-stack-w-docker/tasks/frontend',
            'full-stack-w-docker/tasks/backend'
          ],
        },
        {
          type: 'category',
          label: 'Permissions',
          items: [
            'full-stack-w-docker/permissions/permissions',
            'full-stack-w-docker/permissions/frontend',
            'full-stack-w-docker/permissions/backend'
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Deploying on AWS',
      items: [{type: 'autogenerated', dirName: 'deploying-on-aws'}],
    },
    'review-and-congrats',
    'what-next',
  ],
  
};

export default sidebars;
